apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d1j8cg9b9-nodejs
  janus-idp.io/tekton: d1j8cg9b9-nodejs
  backstage.io/kubernetes-id: d1j8cg9b9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d1j8cg9b9-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
