apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d1j8cg9b9-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d1j8cg9b9-nodejs 
  name: d1j8cg9b9-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: d1j8cg9b9-nodejs 
